### ISSUE TITLE
official = رسمي

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#91]
I should start to add رسمي wherever the associated authority is "official" - may I?

**Comment by tillgrallert** [comment]
I have not yet found the time to link `<orgNames>` from the master to the authority file. But I shall soon do so.  This would mean that `<orgName>رسمي</orgName>` would can then be added automatically to column 11.

I would like to ask you for the meantime to not manually edit the content of columns 11 and 12 (`@n=11` and `@n=12`). It is so much easier to update them with content from the authority file when we don't have to check for manual changes to the data.

**Comment by Mestyan** [comment]
OK this is why I ask whether I should start cleaning with the authority file or with the master jaraid_source. So do I understand that I should start "cleaning" in the authority file? It appears to me that we can only do manual cleaning of many entries so it is essential to agree in the hierarchy between master jaraid_source and the authority file. I guess the authority file rules ? @tillgrallert

**Comment by tillgrallert** [comment]
Dear @Mestyan,

There are two different steps of cleaning the automatically generated Arabic (as per issue #82):

1. Master file: the periodical titles in column (`@n="10"`) need to be corrected in the master file.
2. Authority file: all other entities, i.e. people, places, and organizations need to be corrected in the authority file.
    - Any manual changes to the columns `@n="11"` and `@n="12"` of the master file will be overwritten the next time we import corrections from the authority file.

**Comment by Mestyan** [comment]
@tillgrallert thanks now I understand! Although I still do not see clearly the logic / technical details - would you have time (and good internet) in Beirut to have a chat and educate me about this during the weekend?

**Comment by tillgrallert** [comment]
Yes. Let's do that. There will be a new lockdown for Beirut and Lebanon starting on Saturday so there will be plenty of time.
–––––––––––––––––––––––––––––––––––––––––––
Till Grallert


"'cloud computing' is just a euphemism for 'some dark bunker in Idaho or Utah.'” (E.Morozov)

Please avoid using email accounts subject to unmitigated scrutiny by private companies and government agencies and reply to till.grallert AT posteo.de.

Use encryption whenever possible. Tools for encrypting your emails with PGP (Pretty Good Privacy) can be found at http://www.gpg4win.org/ (Windows) and https://gpgtools.org (Mac OSX). Open Whisper Systems's Signal provides encrypted messaging and VoIP for all major platforms (https://signal.org). Jitsi (https://jitsi.org/) provides open source encrypted VoIP services. Adium (OSX), Jitsi, and ChatSecure (iOS) support OTR (Off The Record) encryption for Jabber, Google Talk, Facebook chat etc. If you want to replace Dropbox etc., with a decentralised and fully encrypted alternative have a look at Resilio Sync (https://www.resilio.com/).

**Comment by Mestyan** [comment]
I sent an email suggesting 8 pm Beirut time on Saturday but feel free please to suggest when it is convenient

**Comment by Mestyan** [comment]
solved
